### ISSUE TITLE
Could not read DB: Unknown Error: error decoding response body: missing field `label` 

### ISSUE THREAD

**Issue by EvanEdwards** [erikh/saturn#31]
First, thank you for this code!   I just set it up and am trying to get it to work with my Google calendar.  I am getting the following error when using `sui` (and a similar when I use `saturn`).  I am quite familiar with Google APIs and code/cli in general, but a complete novice when it comes to rust and the cargo ecosystem.

```
thread 'tokio-runtime-worker' panicked at 'Could not read DB: Unknown Error: error decoding response body: missing field `label` at line 350 column 6', /home/evan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/saturn-cli-0.3.6/src/ui/state.rs:147:14
```

I installed using a simple `cargo install saturn-cli` and set up OAuth on my Google **Workspace** account (emphasis due to it possibly being relevant), and set the client id and secret.  I ran get-token and set the db-type to `google`.  Any query such as `saturn l --all` or `saturn l -r` fails, however I did set an event for today and it works fine with just `saturn l`

This points to an issue with an event I have in my calendar in the next 30 days, I believe.  Is there a way I could constrain the dates queried or otherwise dump more helpful information for debugging purposes?

(As a side query, and I'll connect it to this issue at the end: is there a option to dump a formatted output that can be parsed and used as input to another script?  JSON or YAML or shell or something?  I was thinking I could just dump it from the CBOR database, but it doesn't look to be stored in `.saturn.db`.  Perhaps that is related to this bug?)

**Comment by erikh** [comment]
ok. I think what happened here is that you need to rm -f $HOME/.saturn.db and run saturn list​ which will re-populate the db.

That said, this is less than desirable by any measure and I'm sorry you're going through this. I'll chip at it tonight and see if I can figure out a solution. Please report back if my workaround worked for you, it will help me write the patch.

Thanks!

------- Original Message -------

**Comment by erikh** [comment]
Regarding the need for a dump command; I avoided this initially because saturn can't back up your google calendar reliably, nor is it the goal of saturn to do so.

That said, I'm not opposed to the idea for limited uses, as long as everyone understands it won't contain everything google calendar does; I'm not even going to try and shave that yak.

Please put in a separate ticket for this request and I will address it.
------- Original Message -------

**Comment by erikh** [comment]
Regarding time windows for querying: please put in another ticket for this feature, I'm happy to do that as well.

------- Original Message -------

**Comment by erikh** [comment]
I put in several issues related to this ticket. #32, #33, #34.

**Comment by erikh** [comment]
can you try latest `main` branch and see if that fixes the DB reading bug? Alternatively, since this was actually in the https://github.com/erikh/gcal dependency, just re-installing `saturn-cli` from crates.io should pick it up and you can try that way; other bugs are fixed in main as well.

**Comment by erikh** [comment]
Oh, and just to add more noise, the bug you were experiencing is because you had a calendar item that probably had a location specified as a part of the metadata. This metadata may *optionally* contain a label, but in my google calendar API library I had accidentally made it required. I hope that helps you understand what is happening.

**Comment by erikh** [comment]
OK I'm pretty sure the core issue here was resolved; I'm closing this ticket. Please see the other issues to track your other concerns.

**Comment by EvanEdwards** [comment]
Sorry to have filed and run -- I had a series of minor emergencies on my end.  Thank you for the fast response; I will take a look in the next few days.  I understand completely what you meant by location having an optional part of the data structure and the code failing when it was not present.
