### ISSUE TITLE
README doesn't say if this works with CalDAV

### ISSUE THREAD

**Issue by gdt** [erikh/saturn#63]
I know it says works locally and with Google, but I'd expect an open-source tool to work with the open standard.   I realize from #62 that this is future work.

It would be great for the README to clarify this, perhaps with a simple

(Saturn does not currently support CalDAV.)

which both conveys status and (very softly) telegraphs your stated intention to have it work eventually.

**Comment by erikh** [comment]
I added #64 to cover this issue. The readme is already quite long and I don't see the value in listing things the project doesn't support. I think it's safe to assume it doesn't support them if they're not mentioned.
